Repository Fuzzworth/sorting_algorithms, pull requests merged in 2023-07, with the labels that each got.

#14 Tasks/task 0
  .gitignore
  0-O
  0-bubble_sort.c
  print_array.c
  print_list.c
  sort.h
Labels: enhancement, good first issue, question

#15 Tasks/task 1
  .gitignore
  1-O
  1-insertion_sort_list.c
  sort.h
Labels: documentation, enhancement, question

#16 Tasks/task 2
  .gitignore
  2-O
  2-selection_sort.c
  sort.h
Labels: documentation, enhancement

#17 Title: Added quick sort
  .gitignore
  3-O
  3-quick_sort.c
  sort.h
Labels: documentation, enhancement, question

#26 Title: Fix Issue with text file
  3-O
Labels: bug

#27 Tasks/task 4
  .gitignore
  100-shell_sort.c
  sort.h
Labels: documentation, enhancement

#28 Title: Fix
  100-shell_sort.c
Labels: bug, enhancement

#29 Title: Fixing Task 3
  3-O
  3-quick_sort.c
Labels: bug

#30 Title: Updated
  102-O
Labels: bug, enhancement

#31 Tasks/task 6
  102-counting_sort.c
  104-O
  106-O
Labels: bug, documentation, enhancement

#32 Title: Fix
  102-counting_sort.c
Labels: documentation, enhancement

#35 Tasks/task 8
  .gitignore
  104-heap_sort.c
  sort.h
Labels: documentation, enhancement
